"""
Generate figures for Matouqin result analysis
"""

# install kaleido       # use for save figures generated by plotly

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib.gridspec as gridspec
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
import plotly.graph_objects as pgo
import plotly.io as pio
from plotly.subplots import make_subplots
import pandas as pd
import pyomo.environ as pe
import numpy as np
import math
import re


def set_plt_format():
    plt.rcParams.update({
        'font.family': 'Times New Roman',
        'axes.titlesize': '15',  # title size
        'axes.titlepad': 12,  # space between title and figure
        'axes.labelsize': '13',  # axis title size
        'axes.labelpad': 5,  # space between label and figure
        'xtick.labelsize': '10',  # axis scale size
        'ytick.labelsize': '10',  # axis scale size
        'legend.fontsize': '10',  # legend font size
        'legend.title_fontsize': '13',  # legend title font size
        'font.size': '10',  # font size
        })


def set_pgo_format():
    pgo_templ1 = pgo.layout.Template(
        layout=pgo.Layout(
            width=1000, height=800,
            font=dict(family="Times New Roman", size=13, color="black"),
            titlefont=dict(size=15),
            xaxis=dict(showline=True, linecolor='black',
                       linewidth=1, mirror=True,
                       showgrid=False, showticklabels=True,
                       tickfont=dict(size=13),
                       title_standoff=12,
                       ),
            yaxis=dict(showline=True, linecolor='black',
                       linewidth=1, mirror=True,
                       showgrid=False, showticklabels=True,
                       tickfont=dict(size=13),
                       title_standoff=12,
                       ),
            # legend=dict(x=0.325, y=0.98, traceorder="normal",
            #             font=dict(size=12),
            #             bgcolor="white",
            #             bordercolor="Black", borderwidth=1,
            #             xanchor='center', yanchor='top', orientation="h",
            #             )
        )
    )

    # set new template as default
    pio.templates["pgo_templ1"] = pgo_templ1
    pio.templates.default = "pgo_templ1"


def set_color(numbers):
    n = numbers
    colors = []
    if n == 2:
        # light pink and purple
        # colors = ['#ffbeb4', '#b3c2ff']

        # bule and pink
        colors = ['#0c7bb3', '#f2bae8']

        # orange and yellow
        # colors = ['#f9957f', '#f2f5d0']

        # yellow and blue
        # colors = ['#eae5c9', '#6cc6cb']

        # purple and yellow
        # colors = ['#9fa5d5', '#e8f5c8']
    elif n == 3:
        # gray, blue and orange
        colors = ['#a5a5a5', '#599bd5', '#f7d8b5']

    elif n == 4:
        # white, gray, green and blue
        colors = ['#f4f3f3', '#dfdfdf', '#bfd8d5', '#b1bed5']

        # pink, blue, and silver
        # colors = ['#f9ecec', '#f0d9da', '#c8d9e8', '#ecf2f9']

        # blue, purple, azure and light green
        # colors = ['#69779b', '9692af', '#acdbdf', 'd7eaea']

        # white and green
        # colors = ['#ffffff', '#f0f5f2', '#adc2b5', '#829d93']

        # pink white and blue
        # colors = ['#e3a6ae', '#eecece', '#f7f7f7', '#87c8c8']

        # orange and brown
        # colors = ['#ebc1a7', '#e8dac7', '#f5f2f0', '#cbc088']

        # grey and brown
        # colors = ['#89c5c5', '#e7e5e4', '#d4cfca', '#aea79c']
    elif n == 5:
        # blue to orange
        colors = ['#001b2e', '#294c60', '#adb6c4', '#ffefd3', '#ffc49b']

        # purple to orange
        # colors = ['#885a89', '#8aa8a1', '#cbcbd4', '#d1b490', '#ee7b30']
    elif 5 < n <= 8:
        # blue
        # colors = ['#092b58', '#2f5e8a', '#466a84', '#7ba3d6', '#d5d6da',
        #           '#9e9ea0', '#7f714c', '#4d5848', '#903e28']

        # green
        colors = ['#b7c7ac', '#8aa58b', '#8bb6b8', '#7dc1ea', '#578498',
                  '#334a75', '#e3a98c', '#3b5e57']
    elif 8 < n <= 10:
        # brown
        colors = ['#56442c', '#61523d', '#796d57', '#89785c', '#a59a7d',
                  '#d7d5c6', '#c4cec6', '#8ea2a9', '#698286', '#727b76']
    elif n > 10:
        # blue and yellow as main colors
        colors = ['#235f93', '#3b5e57', '#ee7d2f', '#a5a6a3', '#febf0e',
                  '#70ae4a', '#599cd3', '#1f4575', '#9f4a25', '#636562',
                  '#98742c']

    return colors


def add_labels(bars, values, axs, precision, offset):
    for bar, value in zip(bars, values):
        offset = offset
        pre = precision
        ax = axs
        if value != 0:
            if value > 0:
                # y_position = value + offset
                y_position = bar.get_height() + offset
                va_position = 'bottom'
            else:
                # y_position = value - offset
                y_position = bar.get_height() - offset
                va_position = 'top'
            ax.text(bar.get_x() + bar.get_width() / 2, y_position, f'{bar.get_height():{pre}}',
                    ha='center', va=va_position, fontsize=10)


def show_figs():
    plt.show()


class Plot:
    def __init__(self, rep_dir, figs_dir, data_file):
        self.res_dir = rep_dir          # results directory
        self.fig_dir = figs_dir         # figures directory
        self.dat_file = data_file       # ampl formate data file

        self.finance_df = pd.DataFrame()
        self.cap_df = pd.DataFrame()
        self.supply_df = pd.DataFrame()
        self.flow_df = pd.DataFrame()
        self.dvflow_df = pd.DataFrame()
        self.unit = ''

        self.readCsv()          # read result from csv
        # self.par = self.readPar()         # read needed parameter from .dat file

        # read data from excel
        # self.pl_excel = f'{self.res_dir}plot_vars.xlsx'
        # self.readExcel()

        # # print and check
        # print(f'Finance results:\n {self.finance_df} \n')
        # print(f'Capacity results:\n {self.cap_df} \n')
        # print(f'Supply results:\n {self.supply_df} \n')
        # print(f'Flow results:\n {self.flow_df.head(10)} \n')
        # print(f'Dv_flow results:\n {self.dvflow_df} \n')
        # print(self.cap_df.dtypes)

        # set format
        set_plt_format()
        set_pgo_format()

        # self.plot_finance()
        # self.plot_capacity()
        # self.plot_dv_flow()
        # self.plot_flow()

    def readExcel(self):
        self.finance_df = pd.read_excel(self.pl_excel, sheet_name='finance', index_col=0)
        self.cap_df = pd.read_excel(self.pl_excel, sheet_name='capacity', index_col=0)
        self.supply_df = pd.read_excel(self.pl_excel, sheet_name='supply', index_col=0)
        self.flow_df = pd.read_excel(self.pl_excel, sheet_name='flow', index_col=0)
        self.dvflow_df = pd.read_excel(self.pl_excel, sheet_name='dvflow', index_col=0)

    def readCsv(self):
        self.finance_df = pd.read_csv(f'{self.res_dir}finance.csv', index_col=0)
        self.cap_df = pd.read_csv(f'{self.res_dir}capacity.csv', index_col=0)
        self.supply_df = pd.read_csv(f'{self.res_dir}supply.csv', index_col=0)
        self.flow_df = pd.read_csv(f'{self.res_dir}flow.csv', index_col=0)
        self.dvflow_df = pd.read_csv(f'{self.res_dir}dvflow.csv', index_col=0)

    def readPar(self):
        data = {}

        with open(self.dat_file, 'r') as file:
            content = file.read()

            nhrs = re.search(r'param nHrs :=\s*([\d.]+)\s*;', content, re.DOTALL)
            if nhrs:
                data['nHrs'] = float(nhrs.group(1))
                print(f'nHrs:, {data["nHrs"]}')
            else:
                print(f'nHrs not found')

            eprice = re.search(r'param ePrice :=\s*([\d.]+)\s*;', content, re.DOTALL)
            if eprice:
                data['ePrice'] = float(eprice.group(1))
                print(f'ePrice:, {data["ePrice"]}')
            else:
                print(f'ePrice not found')

            ebprice = re.search(r'param eBprice :=\s*([\d.]+)\s*;', content, re.DOTALL)
            if ebprice:
                data['eBprice'] = float(ebprice.group(1))
                print(f'eBprice:, {data["eBprice"]}')
            else:
                print(f'eBprice not found')

            esprice = re.search(r'param eSprice :=\s*([\d.]+)\s*;', content, re.DOTALL)
            if esprice:
                data['eSprice'] = float(esprice.group(1))
                print(f'eSprice:, {data["eSprice"]}')
            else:
                print(f'eSprice not found')

        return data

    def plot_overview(self):
        print('Overview plotting start')

        # get values
        revenue = self.finance_df['Revenue'].iloc[0]
        if revenue >= 1000:
            self.finance_df = self.finance_df / 1000
            self.unit = 'Million'
        else:
            self.unit = 'Thousand'

        variables = self.finance_df.columns.tolist()
        values = self.finance_df.iloc[0].values
        cap = self.cap_df

        # plotting
        fig = plt.figure(figsize=(10, 8))

        gs = gridspec.GridSpec(2, 2, fig)

        ax1 = fig.add_subplot(gs[0, :])
        ax2 = fig.add_subplot(gs[1, 0])
        ax3 = fig.add_subplot(gs[1, 1])

        color = set_color(3)

        # 1) finance
        bars = ax1.bar(variables, values,
                       color=set_color(7),
                       width=0.5,
                       edgecolor='black',
                       linewidth=0.8, label=variables)
        add_labels(bars, values, ax1, '.2f', 0.01)

        ax1.axhline(0, color='gray', linewidth=0.8, linestyle='--')
        # plt.ylim(-100, 160)    # Set the value range of the y-axis
        # ax1.set_xlabel('Categories')
        ax1.set_ylabel(f'{self.unit} Yuan')
        ax1.set_title('a) Financial Overview', y=-0.2)
        ax1.legend(title='Finance', bbox_to_anchor=(1.02, 1), loc='upper left', borderaxespad=0., edgecolor='black')

        # 2) capacity
        ax22 = ax2.twinx()

        non_tank_dv = cap[~cap.index.str.contains('Tank')]
        tank_dv = cap[cap.index.str.contains('Tank')]

        bars1 = ax2.bar(non_tank_dv.index, non_tank_dv['sCap'], edgecolor='black',
                        color=color, label='Non-Tank (MW)')
        add_labels(bars1, non_tank_dv['sCap'], ax2, '.0f', offset=0)
        ax2.set_title('b) Capacity of the storage system', y=-0.2)
        # ax2.set_xlabel('Storage devices')
        ax2.set_ylabel('Capacity (MW)')
        bars2 = ax22.bar(tank_dv.index, tank_dv['sCap'], edgecolor='black', color=color[2], label='Tank (kg)')
        ax22.set_ylabel('Capacity (thousand kg)')
        add_labels(bars2, tank_dv['sCap'], ax22, '.0f', offset=0)
        # ax2.tick_params(axis='x', rotation=45)

        # 3) number of storage devices
        ax3.bar(non_tank_dv.index, non_tank_dv['sNum'], color=color, edgecolor='black',
                label=non_tank_dv.index)
        ax3.bar(tank_dv.index, tank_dv['sNum'], color=color[2], edgecolor='black',
                label=tank_dv.index)
        ax3.set_title('c) Numbers of storage device', y=-0.2)
        # ax3.set_xlabel('Storage devices')
        ax3.set_ylabel('Numbers')
        # ax3.tick_params(axis='x', rotation=45)

        for idx, val in enumerate(non_tank_dv['sNum']):
            if val != 0:
                ax3.text(idx, val, f'{val}', ha='center', va='bottom')
        for idx, val in enumerate(tank_dv['sNum']):
            if val != 0:
                ax3.text((idx + len(non_tank_dv)), val, f'{val}', ha='center', va='bottom')

        ax3.legend(title='Devices', bbox_to_anchor=(1.05, 1), loc='upper left',
                   borderaxespad=0., edgecolor='black')

        plt.subplots_adjust(top=0.99,
                            bottom=0.08,
                            left=0.069,
                            right=0.87,
                            hspace=0.25,
                            wspace=0.40)

        # fig.tight_layout()
        plt.savefig(f'{self.fig_dir}Finance_overview.png')
        # plt.show()
        # plt.close()

        print('Overview plotting finished \n'
              '--------------------------------')

    def plot_CS(self):
        # cost structure
        self.finance_df[self.finance_df < 1e-5] = 0
        inv = self.finance_df['InvCost'].iloc[0]
        omc = self.finance_df['OMC'].iloc[0]
        surp_cost = self.finance_df['SurpCost'].iloc[0]
        buy_cost = self.finance_df['BuyCost'].iloc[0]
        bal_cost = self.finance_df['BalCost'].iloc[0]
        stor_cost = inv + omc

        revenue = self.finance_df['Revenue'].iloc[0]
        income = self.finance_df['Income'].iloc[0]
        labels = ['Revenue', 'Cost']
        cost = stor_cost + bal_cost

        # inner
        inner_data = [stor_cost, bal_cost]
        inner_labels = ['Stor', 'Bal']

        # outer
        outer_data = [inv, omc, surp_cost, buy_cost]
        outer_labels = ['Inv', 'OMC', 'Surp', 'Buy']

        # text setting
        # def set_text(pct, all_vals):
        #     absolute = int(pct / 100. * sum(all_vals))
        #     #  showing percentages and raw data
        #     return '{:.2f}%\n({:.2f})'.format(pct, absolute)
        #     # return '{:.2f}%'.format(pct)

        # create figure
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 7))

        # setting edges and offsets
        edge_props = dict(edgecolor='black', linewidth=0.8)
        textprops = {'fontsize': 13}
        offset_inner = [0.02] * len(inner_data)          # offset of each outer pie chart
        offset = [0] * len(outer_data)    # offset of each outer pie chart

        # 1) plotting cost and revenue
        wedges1, texts1, autotexts1 = ax1.pie([revenue, cost],
                                              colors=set_color(2),
                                              labels=['Revenue', 'Cost'], textprops=textprops,
                                              labeldistance=0.6,
                                              pctdistance=0.7,
                                              # autopct=lambda pct: set_text(pct, [revenue, cost]),
                                              autopct=lambda pct: f'{pct:.2f}%',
                                              startangle=180,           # start position
                                              wedgeprops=dict(width=0.6, **edge_props),
                                              explode=[0.02, 0.02]      # offset of each sector
                                              )

        # text inside
        ax1.set(aspect='equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
        ax1.text(0, 0, f'Income\n{income:.2f}', horizontalalignment='center', verticalalignment='center',
                 weight='bold', size=15)
        ax1.set_title(f'a) Revenue and cost ({self.unit})', y=-0.2)
        ax1.legend(wedges1, labels, title='Labels', loc='lower center',
                   bbox_to_anchor=(0.5, -0.1), ncol=2)

        # 2) plotting cost structure
        # outer
        wedges2, texts2, autotexts2 = ax2.pie(outer_data, colors=set_color(6),
                                              radius=1,
                                              explode=offset,
                                              labels=outer_labels, textprops=textprops,
                                              labeldistance=0.75,
                                              # autopct=lambda pct: set_text(pct, outer_data),
                                              autopct=lambda pct: f'{pct:.2f}%',
                                              pctdistance=0.88,     # text position, relative to the radius of pie chart
                                              wedgeprops=dict(width=0.3, **edge_props),)

        # inner
        wedges3, texts3, autotexts3 = ax2.pie(inner_data, colors=set_color(4),
                                              radius=1 - 0.4,
                                              explode=offset_inner,
                                              labels=inner_labels, textprops=textprops,
                                              labeldistance=0.55,
                                              # autopct=lambda pct: set_text(pct, inner_data),
                                              autopct=lambda pct: f'{pct:.2f}%',
                                              pctdistance=0.75,     # text position, relative to the radius of pie chart
                                              wedgeprops=dict(width=0.3, **edge_props))

        ax2.set(aspect='equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
        ax2.text(0, 0, f'Cost\n{cost:.2f}', horizontalalignment='center', verticalalignment='center',
                 weight='bold', size=15)
        ax2.set_title(f'b) Cost composition ({self.unit})', y=-0.2)
        ax2.legend(wedges2 + wedges3, outer_labels + inner_labels, title='Cost', loc='lower center',
                   bbox_to_anchor=(0.5, -0.1), ncol=6)

        fig.subplots_adjust(bottom=0.2)
        plt.tight_layout()
        plt.subplots_adjust(top=0.979,
                            bottom=0.172,
                            left=0.011,
                            right=0.971,
                            hspace=0.2,
                            wspace=0.051)
        plt.savefig(f'{self.fig_dir}Cost_pie.png')
        print('Cost plotting finished \n'
              '--------------------------------')

    def plot_finance(self):
        print('Finance plotting start')

        variables = self.finance_df.columns.tolist()
        values = self.finance_df.iloc[0].values

        plt.figure(figsize=(10, 8))
        bars = plt.bar(variables, values, color=set_color(7), edgecolor='black',
                       linewidth=0.8, label=variables)
        add_labels(bars, values, plt, '.2f', 0.01)

        plt.axhline(0, color='gray', linewidth=0.8, linestyle='--')
        # plt.ylim(-100, 160)    # Set the value range of the y-axis
        plt.xlabel('Categories')
        plt.ylabel('Million Yuan')
        plt.title('Financial Overview')
        plt.legend(title='Finance', bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0., edgecolor='black')
        plt.tight_layout()
        plt.savefig(f'{self.fig_dir}Finance_bar.png')
        # plt.show()
        # plt.close()
        print('Finance plotting finished \n'
              '--------------------------------')

    def plot_capacity(self):
        print('Capacity plotting start')

        # get values
        cap = self.cap_df

        # 1) sCap
        # plotting
        fig, axs = plt.subplots(1, 2, figsize=(12, 5))
        color = set_color(3)

        ax2 = axs[0].twinx()

        non_tank_dv = cap[~cap.index.str.contains('Tank')]
        tank_dv = cap[cap.index.str.contains('Tank')]

        bars1 = axs[0].bar(non_tank_dv.index, non_tank_dv['sCap'], edgecolor='black',
                           color=color, label='Non-Tank (MW)')
        add_labels(bars1, non_tank_dv['sCap'], axs[0], '.0f', offset=0)
        axs[0].set_title('Capacity of the storage system')
        axs[0].set_xlabel('Storage devices')
        axs[0].set_ylabel('Capacity (MW)')
        bars2 = ax2.bar(tank_dv.index, tank_dv['sCap'], edgecolor='black', color=color[2], label='Tank (kg)')
        ax2.set_ylabel('Capacity (kg)')
        for bar in bars2:
            if bar.get_height() != 0:
                ax2.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f'{bar.get_height()}',
                         ha='center', va='bottom')

        # axs[2].tick_params(axis='x', rotation=45)

        # 2) sNum
        axs[1].bar(non_tank_dv.index, non_tank_dv['sNum'], color=color, edgecolor='black',
                   label=non_tank_dv.index)
        axs[1].bar(tank_dv.index, tank_dv['sNum'], color=color[2], edgecolor='black',
                   label=tank_dv.index)
        axs[1].set_title('Numbers of storage device')
        axs[1].set_xlabel('Storage devices')
        axs[1].set_ylabel('Numbers')
        # axs[2].tick_params(axis='x', rotation=45)

        for idx, val in enumerate(non_tank_dv['sNum']):
            if val != 0:
                axs[1].text(idx, val, f'{val}', ha='center', va='bottom', fontsize=12)
        for idx, val in enumerate(tank_dv['sNum']):
            if val != 0:
                axs[1].text((idx+len(non_tank_dv)), val, f'{val}', ha='center', va='bottom', fontsize=12)

        axs[1].legend(title='Devices', bbox_to_anchor=(1.05, 1), loc='upper left',
                      borderaxespad=0., edgecolor='black')

        plt.subplots_adjust(left=0.1,
                            right=0.95,
                            bottom=0.1,
                            top=0.9,
                            hspace=0.4,
                            wspace=0.55)

        fig.tight_layout()
        plt.savefig(f'{self.fig_dir}Cap_bar.png')
        # plt.show()

        print('Capacity plotting finished \n'
              '--------------------------------')

    def plot_flow(self, step='hourly', val_show=False, fig_show=True, fig_save=False):
        print(f'Flow plotting start')

        supply_h = self.supply_df['supply'].iloc[0]
        avg_h = self.supply_df['avg_inflow'].iloc[0]
        flow = self.flow_df.copy()

        # print(self.flow_df.head(10))
        # print(flow.head(10))

        # fig = pgo.Figure()
        fig = make_subplots(rows=2, cols=1)

        # set date index
        n = flow.index[-1] + 1  # numbers of periods
        n_index = pd.DataFrame(flow.index, columns=['Index'])       # index, number
        time_deltas = pd.to_timedelta(flow.index, unit='h')
        start_date = pd.Timestamp('2019-01-01 00:00')
        date_times = start_date + time_deltas                       # change index number to date
        flow.index = date_times

        if step == 'hourly':
            agg_df = flow
            avg_inflow = avg_h
            supply = supply_h
            p_avg_inflow = f'Average hourly inflow = {round(avg_inflow, 2)} MW'
            p_supply = f'Average hourly supply = {round(supply, 2)} MW'
            print('step = hourly')

        elif step == 'daily':
            agg_df = flow.resample('D').sum()
            n_day = round((n/24), 2)
            avg_inflow = flow['inflow'].sum() / n_day
            supply = supply_h * 24
            p_avg_inflow = f'Average daily inflow = {round(avg_inflow, 2)} MW'
            p_supply = f'Average daily supply = {round(supply, 2)} MW'
            print('step = daily')

        elif step == 'weekly':
            n_week = round((n / 24 / 7), 2)
            agg_df = flow.resample('7D', origin=start_date).sum()
            avg_inflow = flow['inflow'].sum() / n_week
            supply = supply_h * 168
            p_avg_inflow = f'Average weekly inflow = {round(avg_inflow, 2)} MW'
            p_supply = f'Average weekly supply = {round(supply, 2)} MW'
            fig.update_xaxes(tickvals=agg_df.index)     # make sure the first week begin from Jan.01
            print('step = weekly')

        elif step == 'monthly':
            agg_df = flow.resample('ME').sum()
            n_month = round((n/24/30), 2)
            avg_inflow = flow['inflow'].sum() / n_month
            supply = supply_h * 30
            p_avg_inflow = f'Average monthly inflow = {round(avg_inflow, 2)} MW'
            p_supply = f'Average monthly supply = {round(supply, 2)} MW'
            fig.update_xaxes(tickvals=agg_df.index)     # make sure the tick values match the bars
            print('step = monthly')

        elif step == 'original':
            agg_df = flow
            agg_df.index = n_index.index
            avg_inflow = avg_h
            supply = supply_h
            p_avg_inflow = f'Average inflow = {round(avg_inflow, 2)} MW'
            p_supply = f'Average supply = {round(supply, 2)} MW'
            print('step = original')

        else:
            raise ValueError(f'Invalid step')

        # print(f'{agg_df.head(10)}')

        # plot flows generated by the model
        for i, variable in enumerate(agg_df.columns[1:]):
            if val_show:
                fig.add_trace(pgo.Bar(x=agg_df.index, y=agg_df[variable], name=variable,
                                      text=agg_df[variable],
                                      textposition='auto',
                                      marker=dict(color=set_color(11)[i],
                                                  # line=dict(color='black', width=1)
                                                  ),
                                      ),
                              row=1, col=1,
                              )
            else:
                fig.add_trace(pgo.Bar(x=agg_df.index, y=agg_df[variable], name=variable,
                                      # text=y,
                                      textposition='auto',
                                      marker=dict(color=set_color(11)[i],
                                                  # line=dict(color='black', width=1)
                                                  ),
                                      ),
                              row=1, col=1,
                              )

        fig.update_yaxes(title_text=f'{step.capitalize()} Flows (MW)',
                         # range=[-30, 16],
                         row=1, col=1)

        fig.add_shape(type="line",
                      x0=(agg_df.index[0]), y0=0,
                      x1=(agg_df.index[-1]), y1=0,
                      line=dict(color="gray", width=2, dash="dot"),
                      showlegend=False,
                      row=1, col=1,
                      )     # add a line: y = 0

        fig.add_shape(type="line",
                      x0=(agg_df.index[0]), y0=supply,
                      x1=(agg_df.index[-1]), y1=supply,
                      line=dict(color="grey", width=2, dash="dot"),
                      row=1, col=1,
                      )     # add a line: y = supply

        fig.add_annotation(x=(agg_df.index[0]), y=(1.15 * supply),
                           text=p_supply,
                           font=dict(size=18),
                           bgcolor='#f5f5f5',
                           showarrow=False,
                           xanchor='left',  # starting from the left side of the x coordinate
                           row=1, col=1,
                           )       # add text for supply

        # plot inflow at bottom
        if val_show:
            fig.add_trace(pgo.Bar(x=agg_df.index, y=agg_df['inflow'], name='inflow',
                                  text=agg_df['inflow'],
                                  textposition='auto',
                                  marker=dict(color=set_color(11)[-1]
                                              # line=dict(color='black', width=1)
                                              ),
                                  ),
                          row=2, col=1,
                          )
        else:
            fig.add_trace(pgo.Bar(x=agg_df.index, y=agg_df['inflow'], name='inflow',
                                  # text=agg_df['inflow'],
                                  textposition='auto',
                                  marker=dict(color=set_color(11)[-1]
                                              # line=dict(color='black', width=1)
                                              ),
                                  ),
                          row=2, col=1,
                          )

        fig.update_yaxes(title_text=f'{step.capitalize()} Inflow (MW) ', row=2, col=1)

        fig.add_shape(type="line",
                      x0=(agg_df.index[0]), y0=avg_inflow,
                      x1=(agg_df.index[-1]), y1=avg_inflow,
                      # xref="paper",
                      # yref="y",
                      line=dict(color="grey", width=2, dash="dot"),
                      row=2, col=1,
                      )     # add line: y = average inflow

        fig.add_annotation(x=(agg_df.index[0]), y=(1.05 * avg_inflow),
                           text=p_avg_inflow,
                           font=dict(size=18),
                           bgcolor='#f5f5f5',
                           showarrow=False,
                           xanchor='left',  # starting from the left side of the x coordinate
                           row=2, col=1,
                           )    # add text of average inflow

        # set layout
        fig.update_xaxes(title_text='Time',
                         # tickvals=agg_df.index,
                         tickformat='%b %d',
                         tickangle=45,
                         nticks=12,
                         # row = 2, col = 1,
                         )  # set both axes layout

        fig.update_yaxes(nticks=7)

        fig.update_layout(
            # barmode='stack',
            barmode='relative',     # positive and negative values are displayed relative to 0
            # bargap=0,   # set the spacing between the bars
            title='Flow overview',
            legend_title='Variables',
            plot_bgcolor='white',   # background color
            width=1400, height=800,
        )

        if fig_show:
            fig.show()

        if fig_save:        # need to install 'kaleido'
            # fig.write_image(f'{self.fig_dir}{step}_flow_overview.png')    # save as png file (static)
            fig.write_html(f'{self.fig_dir}{step}_flow_overview.html')    # save as html file (interactive)

        print('Flow overview plotting finished \n'
              '--------------------------------')

    def plot_dv_flow(self, n, unit='day'):
        # print hourly flows in specific day or week
        print(f'Plotting energy flows in the {unit} {n} start')

        # get values
        dv_ele_df = self.dvflow_df.filter(like='Elec')
        dv_hy_df = self.dvflow_df.filter(like='Tank')
        dv_fc_df = self.dvflow_df.filter(like='Cell')

        flow_h_df = self.flow_df.copy()
        flow_h_df = flow_h_df.abs()         # all positive values
        supply_h = self.supply_df['supply'].iloc[0]

        # plotting
        fig, axs = plt.subplots(4, 1, figsize=(12, 12))

        # data processing, day, week
        if unit == 'day':
            dv_ele = dv_ele_df.iloc[((n - 1) * 24):(n * 24)]
            dv_hy = dv_hy_df.iloc[((n - 1) * 24):(n * 24)]
            dv_fc = dv_fc_df.iloc[((n - 1) * 24):(n * 24)]
            flow = flow_h_df.iloc[((n - 1) * 24):(n * 24)]

            for ax in axs:
                ax.xaxis.set_major_locator(ticker.MultipleLocator(4))

        elif unit == 'week':
            dv_ele = dv_ele_df.iloc[((n - 1) * 168):(n * 168)]
            dv_hy = dv_hy_df.iloc[((n - 1) * 168):(n * 168)]
            dv_fc = dv_fc_df.iloc[((n - 1) * 168):(n * 168)]
            flow = flow_h_df.iloc[((n - 1) * 168):(n * 168)]

            for ax in axs:
                ax.xaxis.set_major_locator(ticker.MultipleLocator(24))

        else:
            raise ValueError(f'Invalid unit')

        # 1) flows overview
        if flow.empty:
            print(f'There is no energy flows in the model, please check')
        else:
            flow.plot(ax=axs[0],
                      kind='bar',
                      # color=set_color(9)
                      )
            axs[0].axhline(y=supply_h, color='grey', linestyle='--')
            axs[0].axhline(y=0, color='black', linestyle=':')
            axs[0].text(flow.index[0], supply_h, f'Supply = {round(supply_h, 2)}',
                        verticalalignment='bottom', horizontalalignment='left')

        axs[0].legend(bbox_to_anchor=(1.15, 1.02), loc='upper center', ncol=1)
        axs[0].set_title(f'a) Electricity flows in the {n} {unit}', y=-0.5)
        axs[0].set_xlabel('Time')
        axs[0].set_ylabel('Electricity flow (MW)')
        axs[0].tick_params(axis='x', rotation=0)

        # 1) electrolyzer flows
        if dv_ele.empty:
            print(f'There is no energy flows through the electrolyzer')
        else:
            # dv_ele_p = dv_ele.loc[:, (dv_ele != 0).any(axis=0)]     # remove 0 columns
            # dv_ele_p.plot(ax=axs[0],
            dv_ele.plot(ax=axs[1],
                        # kind='bar', width=0.8,
                        # edgecolor='black',
                        )

            max_val = dv_ele.max().max()
            min_val = dv_ele.min().min()

            max_t = dv_ele.idxmax().loc[dv_ele.max().idxmax()]
            min_t = dv_ele.idxmin().loc[dv_ele.min().idxmin()]

            axs[1].annotate(f'{max_val:.2f}', xy=(max_t, max_val), xytext=(max_t, 1.01 * max_val))
            # arrowprops=dict(facecolor='black', shrink=0.05)
            axs[1].annotate(f'{min_val:.2f}', xy=(min_t, min_val), xytext=(min_t, 1.01 * (min_val-0.1)))
            # arrowprops=dict(facecolor='black', shrink=0.05))

            axs[1].axhline(y=0, color='black', linestyle=':')

            axs[1].set_ylim([(min_val - 2), (max_val + 2)])
            axs[1].legend(bbox_to_anchor=(1.15, 1.02), loc='upper center', ncol=1)
            axs[1].set_title(f'b) Electricity flow in eltrolyzer', y=-0.5)
            axs[1].set_xlabel('Time')
            axs[1].set_ylabel('Electricity flow (MW)')
            axs[1].tick_params(axis='x', rotation=0)

        # 2) hydrogen flows
        if dv_hy.empty:
            print(f'There is no energy flows through the hydrogen tank')
        else:
            # dv_hy = dv_hy.loc[:, (dv_hy != 0).any(axis=0)]  # remove 0 columns

            dv_hy_in = dv_hy.filter(like='hIn')
            dv_hy_out = dv_hy.filter(like='hOut')
            dv_hy_vol = dv_hy.filter(like='hVol')

            mmax = dv_hy_in.max().max()
            mmin = dv_hy_out.min().min()
            hmax = dv_hy_vol.max().max()

            max_idx = dv_hy_in.idxmax().loc[dv_hy_in.max().idxmax()]
            min_idx = dv_hy_out.idxmin().loc[dv_hy_out.max().idxmax()]
            hmax_idx = dv_hy_vol.idxmax().loc[dv_hy_vol.max().idxmax()]

            axs[2].annotate(f'{mmax:.2f}',
                            xy=(max_idx, mmax),
                            xytext=(max_idx, mmax * 1.05),
                            ha='center')
            axs[2].annotate(f'{mmin:.2f}',
                            xy=(min_idx, mmin),
                            xytext=(min_idx, mmin * 1.05),
                            ha='center')
            axs[2].annotate(f'{hmax:.2f}',
                            xy=(hmax_idx, hmax),
                            xytext=(hmax_idx, hmax * 1.05),
                            ha='center')

            axs[2].axhline(y=0, color='black', linestyle=':')

            dv_hy.plot(ax=axs[2],
                       # kind='bar', width=0.8,
                       # edgecolor='black',
                       )

            # for container in axs[2].containers:
            #     axs[2].bar_label(container)

            axins = inset_axes(axs[2], width='70%', height='55%', loc='lower right',
                               bbox_to_anchor=(0.4, 0.2, 0.6, 0.6),
                               bbox_transform=axs[2].transAxes)
            dv_hy.plot(ax=axins, legend=False)
            axins.set_ylim(1.1 * (mmin-3), 1.1 * (mmax+3))

            # hide axes or labels
            # axins.set_xlabel('Time (zoomed in)')
            # axins.set_ylabel('Flow (zoomed in)')
            # axins.tick_params(labelleft=False, labelbottom=False)

            axs[2].set_ylim([(mmin - 2), (hmax + 2)])
            axs[2].legend(bbox_to_anchor=(1.15, 1.02), loc='upper center', ncol=1)
            axs[2].set_title(f'c) Hydrogen flow in hydrogen tanks', y=-0.5)
            axs[2].set_xlabel('Time')
            axs[2].set_ylabel('Hydrogen flow (100 kg)')
            axs[2].tick_params(axis='x', rotation=0)

        # 3) Fuel-cell flows
        if dv_fc.empty:
            print(f'There is no energy flows through the fuel cell')
        else:
            # dv_fc_p = dv_fc.loc[:, (dv_fc != 0).any(axis=0)]      # remove 0 columns
            # fc_h = dv_fc_p.filter(like='hInc')
            # fc_e = dv_fc_p.filter(like='cOut')
            fc_h = dv_fc.filter(like='hInc')
            fc_e = dv_fc.filter(like='cOut')

            max_h = fc_h.max().max()
            min_h = fc_h.min().min()
            max_e = fc_e.max().max()
            min_e = fc_e.min().min()

            max_ht = fc_h.idxmax().loc[fc_h.max().idxmax()]
            min_ht = fc_h.idxmin().loc[fc_h.min().idxmin()]
            max_et = fc_e.idxmax().loc[fc_e.max().idxmax()]
            min_et = fc_e.idxmin().loc[fc_e.min().idxmin()]

            fc_e.plot(ax=axs[3], xlabel='Time', ylabel='Electricity flow (MW)', legend=False)
            # kind='bar', width=0.8, edgecolor='black',
            axs[3].annotate(f'{max_e:.2f}', xy=(max_et, max_e), xytext=(max_et, max_e * 1.05))
            axs[3].annotate(f'{min_e:.2f}', xy=(min_et, min_e), xytext=(min_et, min_e * 1.05))
            #

            axs[3].axhline(y=0, color='black', linestyle=':')

            ax3 = axs[3].twinx()
            fc_h.plot(ax=ax3, ylabel='Hydrogen (kg)', color='pink', legend=False)
            # # kind='bar', width=0.8, # edgecolor='black',
            ax3.annotate(f'{max_h:.2f}', xy=(max_ht, max_h), xytext=(max_ht, max_h * 1.05))
            ax3.annotate(f'{min_h:.2f}', xy=(min_ht, max_h), xytext=(min_ht, min_h * 1.05))

            # for container in axs[2].containers:
            #     axs[2].bar_label(container)

            # ax2.legend(bbox_to_anchor=(1.11, 1.02), loc='upper left', ncol=1)
            # axs[2].legend(bbox_to_anchor=(1.2, 0.85), loc='upper left', ncol=1)
            axs[3].set_ylim([(min_e - 2), (max_e + 2)])
            lines, labels = axs[3].get_legend_handles_labels()
            lines2, labels2 = ax3.get_legend_handles_labels()
            axs[3].legend(lines + lines2, labels + labels2, bbox_to_anchor=(1.1, 1.02), loc='upper left', ncol=1)

            axs[3].tick_params(axis='x', rotation=0)

            axs[3].set_title(f'd) Energy flows in fuel cells', y=-0.5)

            # set x coordinate interval
            # for ax in axs:
            #     ax.xaxis.set_major_locator(ticker.MultipleLocator(24))

        for ax in axs.flatten():
            ax.yaxis.set_major_locator(ticker.MaxNLocator(5))
            ax.xaxis.set_major_locator(ticker.MaxNLocator(13))

        plt.subplots_adjust(top=0.981,
                            bottom=0.108,
                            left=0.083,
                            right=0.809,
                            hspace=0.6,
                            wspace=0.2)

        # plt.tight_layout()
        # fig.set_constrained_layout(True)

        print('Dv flows plotting finished \n'
              '--------------------------------')

        plt.savefig(f'{self.fig_dir}Dvflows.png')


# ----------------------------------------------------------------
# path = '.'
# res_dir = f'{path}/Results/'        # repository of results
# fig_dir = f'{path}/Figures/'        # repository of figures
# f_data = f'{path}/Data/test1.dat'   # data file
#
# Fig = Plot(res_dir, fig_dir, f_data)
# Fig.plot_CS()

# # Flow overview, 'hourly', 'daily', 'weekly', 'monthly', 'original' flows; 'original' use for model test results
# # 'kaleido' is needed for fig_save: True
# Fig.plot_flow('original', True, True, True)
# Fig.plot_flow('daily', False, True, False)
# # Fig.plot_flow('weekly', False, False)
# # Fig.plot_flow('monthly', False, False)
#
# Fig.plot_overview()  # Finance and storage overview
# Fig.plot_dv_flow(5, 'week')  # Detailed flow of storage system, unit: 'day', 'week'
#
# # fig.plot_finance()      # Finance overview
# # fig.plot_capacity()     # Storage capacity
#
# show_figs()  # show figures
